#include <sstream>

std::string getControlScene(const std::string& instanceId, const std::string& quadrantId) {
    std::ostringstream ret;

    ret << ""
        << "<svg:svg xmlns:krb=\"http://karabo.eu/scene\" xmlns:svg=\"http://www.w3.org/2000/svg\" krb:version=\"2\" krb:uuid=\"dc0b7df2-f0d3-400a-b6c9-9d4ae0444980\" height=\"532\" width=\"1121\"><svg:rect stroke=\"#000000\" stroke-opacity=\"1.0\" stroke-linecap=\"butt\" stroke-dashoffset=\"0.0\" stroke-width=\"1.0\" stroke-dasharray=\"\" stroke-style=\"1\" stroke-linejoin=\"miter\" stroke-miterlimit=\"4.0\" fill=\"#ffffff\" fill-opacity=\"1.0\" x=\"17\" y=\"20\" width=\"760\" height=\"246\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".initSystem\" x=\"27\" y=\"115\" width=\"111\" height=\"31\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".resetASICs\" x=\"27\" y=\"175\" width=\"111\" height=\"21\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"367\" y=\"135\" width=\"171\" height=\"21\" krb:text=\"PLL Locked\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".readLastPPTTrainID\" x=\"157\" y=\"175\" width=\"181\" height=\"21\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"157\" y=\"195\" width=\"91\" height=\"21\" krb:text=\"Last Train ID\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".lastTrainId\" x=\"227\" y=\"195\" width=\"111\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".startAllChannelsDummyData\" x=\"578\" y=\"475\" width=\"180\" height=\"21\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".stopAcquisition\" x=\"157\" y=\"45\" width=\"181\" height=\"51\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".runXFEL\" x=\"157\" y=\"95\" width=\"181\" height=\"51\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".open\" x=\"27\" y=\"45\" width=\"111\" height=\"31\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".close\" x=\"27\" y=\"75\" width=\"111\" height=\"31\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:g krb:class=\"FixedLayout\" krb:x=\"578\" krb:y=\"295\" krb:height=\"111\" krb:width=\"181\"><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".checkPPTDataFailed," << instanceId << ".initSystem\" x=\"578\" y=\"295\" width=\"181\" height=\"31\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"Evaluator\" krb:keys=\"" << instanceId << ".pptChannelFailed.failedChannel1\" x=\"578\" y=\"325\" width=\"181\" height=\"21\" expression=\"'{:016b}'.format(x)\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"Evaluator\" krb:keys=\"" << instanceId << ".pptChannelFailed.failedChannel2\" x=\"578\" y=\"345\" width=\"181\" height=\"21\" expression=\"bin(x)[2:].zfill(16)\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"Evaluator\" krb:keys=\"" << instanceId << ".pptChannelFailed.failedChannel3\" x=\"578\" y=\"365\" width=\"181\" height=\"21\" expression=\"'{:016b}'.format(x)\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"Evaluator\" krb:keys=\"" << instanceId << ".pptChannelFailed.failedChannel4\" x=\"578\" y=\"385\" width=\"181\" height=\"21\" expression=\"bin(x)[2:].zfill(16)\" "
        << "/>"
        << "</svg:g><svg:g krb:class=\"FixedLayout\" krb:x=\"578\" krb:y=\"405\" krb:height=\"41\" krb:width=\"181\"><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".checkQSFPConnected\" x=\"578\" y=\"405\" width=\"181\" height=\"21\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"578\" y=\"425\" width=\"107\" height=\"21\" krb:text=\"Connected QSFPs\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".connectedETHChannels\" x=\"685\" y=\"425\" width=\"74\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayStateColor\" krb:keys=\"" << instanceId << ".state\" x=\"367\" y=\"45\" width=\"171\" height=\"31\" krb:show_string=\"true\" "
        << "/>"
        << "<svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"367\" krb:y=\"75\" krb:height=\"21\" krb:width=\"201\"><svg:rect krb:class=\"Label\" x=\"367\" y=\"75\" width=\"98\" height=\"21\" krb:text=\"Alarm condition\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".alarmCondition\" x=\"465\" y=\"75\" width=\"103\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"367\" krb:y=\"95\" krb:height=\"21\" krb:width=\"201\"><svg:rect krb:class=\"Label\" x=\"367\" y=\"95\" width=\"130\" height=\"21\" krb:text=\"PPT FPGA Temp.\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".pptTemp\" x=\"497\" y=\"95\" width=\"71\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"367\" krb:y=\"115\" krb:height=\"21\" krb:width=\"201\"><svg:rect krb:class=\"Label\" x=\"367\" y=\"115\" width=\"101\" height=\"21\" krb:text=\"SFP Output Rate\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".ethOutputRate\" x=\"468\" y=\"115\" width=\"100\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:g krb:class=\"FixedLayout\" krb:x=\"578\" krb:y=\"455\" krb:height=\"21\" krb:width=\"181\"><svg:rect krb:class=\"Label\" x=\"578\" y=\"455\" width=\"121\" height=\"21\" krb:text=\"Disable Sending\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCheckBox\" krb:keys=\"" << instanceId << ".disable_sending\" x=\"708\" y=\"455\" width=\"31\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"EditableCheckBox\" krb:keys=\"" << instanceId << ".disable_sending\" x=\"738\" y=\"455\" width=\"21\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:rect krb:class=\"Label\" x=\"27\" y=\"215\" width=\"751\" height=\"21\" krb:text=\"Configuration:\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".fullConfigFileName\" x=\"27\" y=\"235\" width=\"741\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"578\" y=\"275\" width=\"181\" height=\"20\" krb:text=\"datachain overview\" krb:font=\"Source Sans Pro,10,-1,5,75,0,0,0,0,0\" krb:foreground=\"#0000ff\" krb:frameWidth=\"0\" krb:background=\"transparent\" krb:alignh=\"4\" "
        << "/>"
        << "<svg:rect stroke=\"#000000\" stroke-opacity=\"1.0\" stroke-linecap=\"butt\" stroke-dashoffset=\"0.0\" stroke-width=\"1.0\" stroke-dasharray=\"\" stroke-style=\"1\" stroke-linejoin=\"miter\" stroke-miterlimit=\"4.0\" fill=\"#ffffff\" fill-opacity=\"1.0\" x=\"557\" y=\"275\" width=\"221\" height=\"236\" "
        << "/>"
        << "<svg:rect stroke=\"#000000\" stroke-opacity=\"1.0\" stroke-linecap=\"butt\" stroke-dashoffset=\"0.0\" stroke-width=\"1.0\" stroke-dasharray=\"\" stroke-style=\"1\" stroke-linejoin=\"miter\" stroke-miterlimit=\"4.0\" fill=\"#ffffff\" fill-opacity=\"1.0\" x=\"17\" y=\"275\" width=\"531\" height=\"236\" "
        << "/>"
        << "<svg:g krb:class=\"FixedLayout\" krb:x=\"27\" krb:y=\"295\" krb:height=\"201\" krb:width=\"241\"><svg:g krb:class=\"FixedLayout\" krb:x=\"27\" krb:y=\"295\" krb:height=\"161\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"27\" y=\"315\" width=\"121\" height=\"21\" krb:text=\"Cycle Length\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.cycleLength\" x=\"147\" y=\"315\" width=\"121\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"27\" y=\"365\" width=\"121\" height=\"21\" krb:text=\"Integration Time\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.integrationTime\" x=\"147\" y=\"365\" width=\"121\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.flattopLength\" x=\"147\" y=\"385\" width=\"121\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"27\" y=\"385\" width=\"121\" height=\"21\" krb:text=\"flat-top time\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".updateSequenceCounters\" x=\"27\" y=\"435\" width=\"241\" height=\"21\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"27\" y=\"295\" width=\"121\" height=\"21\" krb:text=\"Operation Mode\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.opMode\" x=\"147\" y=\"295\" width=\"121\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"27\" y=\"335\" width=\"107\" height=\"21\" krb:text=\"Burst length\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.burstLength\" x=\"147\" y=\"335\" width=\"121\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"27\" y=\"415\" width=\"121\" height=\"21\" krb:text=\"CLR Duty\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.clrDuty\" x=\"147\" y=\"415\" width=\"121\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:g krb:class=\"FixedLayout\" krb:x=\"27\" krb:y=\"455\" krb:height=\"41\" krb:width=\"241\"><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"27\" krb:y=\"455\" krb:height=\"21\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"27\" y=\"455\" width=\"122\" height=\"21\" krb:text=\"Start Wait Offset [10ns] \" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.start_wait_offs\" x=\"149\" y=\"455\" width=\"60\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.start_wait_offs\" x=\"209\" y=\"455\" width=\"59\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".updateStartWaitOffset\" x=\"27\" y=\"475\" width=\"241\" height=\"21\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "</svg:g></svg:g><svg:rect krb:class=\"Label\" x=\"17\" y=\"275\" width=\"541\" height=\"20\" krb:text=\"Timing settings overview\" krb:font=\"Source Sans Pro,10,-1,5,75,0,0,0,0,0\" krb:foreground=\"#0000ff\" krb:frameWidth=\"0\" krb:background=\"transparent\" krb:alignh=\"4\" "
        << "/>"
        << "<svg:g krb:class=\"FixedLayout\" krb:x=\"367\" krb:y=\"165\" krb:height=\"41\" krb:width=\"201\"><svg:rect krb:class=\"Label\" x=\"367\" y=\"165\" width=\"91\" height=\"21\" krb:text=\"Frames to DAQ\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".numFramesToSendOut\" x=\"457\" y=\"165\" width=\"51\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".numFramesToSendOut\" x=\"507\" y=\"165\" width=\"61\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"367\" y=\"185\" width=\"91\" height=\"21\" krb:text=\"Pre-veto\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".numPreBurstVetos\" x=\"457\" y=\"185\" width=\"51\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".numPreBurstVetos\" x=\"507\" y=\"185\" width=\"61\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"InstanceStatus\" krb:keys=\"" << instanceId << ".deviceId\" x=\"537\" y=\"45\" width=\"30\" height=\"30\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"287\" y=\"295\" width=\"261\" height=\"20\" krb:text=\"NORM = double integration\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#7a7a7a\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"287\" y=\"315\" width=\"261\" height=\"21\" krb:text=\"22      = 4.5MHz | 44      = 2.2MHz | 88   = 1.1 MHz \" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#7a7a7a\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"287\" y=\"335\" width=\"261\" height=\"20\" krb:text=\"2701 = 4.5MHz | 1351 = 2.2MHz | 676 = 1.1 MHz\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#7a7a7a\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"287\" y=\"365\" width=\"261\" height=\"41\" krb:text=\"N*1.44ns | 70 = 100ns | 52 = 75ns | 35 = 50ns\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#7a7a7a\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"287\" y=\"415\" width=\"261\" height=\"20\" krb:text=\"4 = 50ns | 9 = 100ns\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#7a7a7a\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"27\" y=\"20\" width=\"751\" height=\"21\" krb:text=\"DSSC " << quadrantId << " control\" krb:font=\"Source Sans Pro,10,-1,5,75,0,0,0,0,0\" krb:foreground=\"#0000ff\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".iob1Status.iob1BuiltStamp\" x=\"617\" y=\"105\" width=\"151\" height=\"31\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"587\" y=\"45\" width=\"31\" height=\"31\" krb:text=\"PPT\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".linuxRev\" x=\"617\" y=\"75\" width=\"151\" height=\"31\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".firmwareRev\" x=\"617\" y=\"45\" width=\"151\" height=\"31\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"587\" y=\"75\" width=\"31\" height=\"31\" krb:text=\"Lin.\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"587\" y=\"105\" width=\"31\" height=\"31\" krb:text=\"IOB\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayErrorBool\" krb:keys=\"" << instanceId << ".pptPLL.locked\" x=\"547\" y=\"135\" width=\"25\" height=\"25\" krb:invert=\"false\" "
        << "/>"
        << "<svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"880\" krb:y=\"110\" krb:height=\"27\" krb:width=\"211\"><svg:rect krb:class=\"Label\" x=\"880\" y=\"110\" width=\"97\" height=\"27\" krb:text=\"Module Number\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".selModule\" x=\"977\" y=\"110\" width=\"57\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".selModule\" x=\"1034\" y=\"110\" width=\"57\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"920\" krb:y=\"140\" krb:height=\"27\" krb:width=\"171\"><svg:rect krb:class=\"Label\" x=\"920\" y=\"140\" width=\"57\" height=\"27\" krb:text=\"Value\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".selValue\" x=\"977\" y=\"140\" width=\"57\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".selValue\" x=\"1034\" y=\"140\" width=\"57\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"2\" krb:class=\"BoxLayout\" krb:x=\"900\" krb:y=\"180\" krb:height=\"75\" krb:width=\"121\"><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".preProgSelReg\" x=\"900\" y=\"180\" width=\"121\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".progSelReg\" x=\"900\" y=\"205\" width=\"121\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".readSelReg\" x=\"900\" y=\"230\" width=\"121\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"920\" krb:y=\"361\" krb:height=\"21\" krb:width=\"170\"><svg:rect krb:class=\"Label\" x=\"920\" y=\"361\" width=\"127\" height=\"21\" krb:text=\"CD\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".gain.rmpCurrDouble\" x=\"1047\" y=\"361\" width=\"43\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"921\" krb:y=\"320\" krb:height=\"21\" krb:width=\"170\"><svg:rect krb:class=\"Label\" x=\"921\" y=\"320\" width=\"85\" height=\"21\" krb:text=\"FCF_EnCap\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".gain.fcfEnCap\" x=\"1006\" y=\"320\" width=\"85\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"921\" krb:y=\"341\" krb:height=\"21\" krb:width=\"170\"><svg:rect krb:class=\"Label\" x=\"921\" y=\"341\" width=\"95\" height=\"21\" krb:text=\"Iramp Fine Trim\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".gain.irampFineTrm\" x=\"1016\" y=\"341\" width=\"75\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:rect krb:class=\"SceneLink\" x=\"860\" y=\"450\" width=\"149\" height=\"27\" krb:background=\"transparent\" krb:text=\"" << quadrantId << " Ladder Configuration\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"\" krb:keys=\"" << instanceId << ".availableScenes\" krb:target=\"configurator\" krb:widget=\"DeviceSceneLink\" krb:frameWidth=\"1\" krb:target_window=\"dialog\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".iob2Status.iob2BuiltStamp\" x=\"617\" y=\"135\" width=\"151\" height=\"31\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".iob3Status.iob3BuiltStamp\" x=\"617\" y=\"165\" width=\"151\" height=\"31\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".iob4Status.iob4BuiltStamp\" x=\"617\" y=\"195\" width=\"151\" height=\"31\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"810\" y=\"20\" width=\"141\" height=\"21\" krb:text=\"Pixels Configuration\" krb:font=\"Source Sans Pro,10,-1,5,75,0,0,0,0,0\" krb:foreground=\"#0000ff\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect stroke=\"#000000\" stroke-opacity=\"1.0\" stroke-linecap=\"butt\" stroke-dashoffset=\"0.0\" stroke-width=\"1.0\" stroke-dasharray=\"\" stroke-style=\"1\" stroke-linejoin=\"miter\" stroke-miterlimit=\"4.0\" fill=\"#ffffff\" fill-opacity=\"1.0\" x=\"790\" y=\"20\" width=\"311\" height=\"491\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".selPixelSignal\" x=\"970\" y=\"70\" width=\"121\" height=\"31\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"EditableComboBox\" krb:keys=\"" << instanceId << ".selPixelSignal\" x=\"810\" y=\"70\" width=\"160\" height=\"31\" "
        << "/>"
        << "</svg:svg>"

        << "";
    return ret.str();
}


std::string getConfiguratorScene(const std::string& instanceId, const std::string& quadrantId) {
    std::ostringstream ret;

    ret << ""
        << "<svg:svg xmlns:krb=\"http://karabo.eu/scene\" xmlns:svg=\"http://www.w3.org/2000/svg\" krb:version=\"2\" krb:uuid=\"3cf60bb0-01da-4606-8d80-650a4f1db890\" height=\"927\" width=\"850\"><svg:g krb:direction=\"2\" krb:class=\"BoxLayout\" krb:x=\"20\" krb:y=\"20\" krb:height=\"50\" krb:width=\"100\"><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".open\" x=\"20\" y=\"20\" width=\"100\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".close\" x=\"20\" y=\"45\" width=\"100\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"2\" krb:class=\"BoxLayout\" krb:x=\"360\" krb:y=\"20\" krb:height=\"84\" krb:width=\"206\"><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayStateColor\" krb:keys=\"" << instanceId << ".state\" x=\"360\" y=\"20\" width=\"206\" height=\"21\" krb:show_string=\"true\" "
        << "/>"
        << "<svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"360\" krb:y=\"41\" krb:height=\"21\" krb:width=\"206\"><svg:rect krb:class=\"Label\" x=\"360\" y=\"41\" width=\"103\" height=\"21\" krb:text=\"Alarm condition\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".alarmCondition\" x=\"463\" y=\"41\" width=\"103\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"360\" krb:y=\"62\" krb:height=\"21\" krb:width=\"206\"><svg:rect krb:class=\"Label\" x=\"360\" y=\"62\" width=\"135\" height=\"21\" krb:text=\"PPT FPGA Temperature\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".pptTemp\" x=\"495\" y=\"62\" width=\"71\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"360\" krb:y=\"83\" krb:height=\"21\" krb:width=\"206\"><svg:rect krb:class=\"Label\" x=\"360\" y=\"83\" width=\"103\" height=\"21\" krb:text=\"SFP Output Rate\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".ethOutputRate\" x=\"463\" y=\"83\" width=\"103\" height=\"21\" "
        << "/>"
        << "</svg:g></svg:g><svg:g krb:direction=\"2\" krb:class=\"BoxLayout\" krb:x=\"580\" krb:y=\"140\" krb:height=\"67\" krb:width=\"221\"><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"580\" krb:y=\"140\" krb:height=\"21\" krb:width=\"221\"><svg:rect krb:class=\"Label\" x=\"580\" y=\"140\" width=\"109\" height=\"21\" krb:text=\"Clone Eth1 to Eth2\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCheckBox\" krb:keys=\"" << instanceId << ".clone_eth0_to_eth1\" x=\"689\" y=\"140\" width=\"56\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"EditableCheckBox\" krb:keys=\"" << instanceId << ".clone_eth0_to_eth1\" x=\"745\" y=\"140\" width=\"56\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".checkQSFPConnected\" x=\"580\" y=\"161\" width=\"221\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"580\" krb:y=\"186\" krb:height=\"21\" krb:width=\"221\"><svg:rect krb:class=\"Label\" x=\"580\" y=\"186\" width=\"147\" height=\"21\" krb:text=\"Connected ETH Channels\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".connectedETHChannels\" x=\"727\" y=\"186\" width=\"74\" height=\"21\" "
        << "/>"
        << "</svg:g></svg:g><svg:rect krb:class=\"Label\" x=\"259\" y=\"530\" width=\"135\" height=\"30\" krb:text=\"SET to 1 ***\" krb:font=\"Source Sans Pro,10,-1,5,75,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"259\" y=\"670\" width=\"61\" height=\"21\" krb:text=\"99\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"259\" y=\"690\" width=\"71\" height=\"31\" krb:text=\"397\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"259\" y=\"450\" width=\"141\" height=\"30\" krb:text=\"2.25MHz: 27 | 4.5MHz: 53\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"259\" y=\"480\" width=\"141\" height=\"21\" krb:text=\"1351 | 2701\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:g krb:direction=\"2\" krb:class=\"BoxLayout\" krb:x=\"150\" krb:y=\"150\" krb:height=\"46\" krb:width=\"181\"><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".checkPPTDataFailed," << instanceId << ".initSystem\" x=\"150\" y=\"150\" width=\"181\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"150\" krb:y=\"175\" krb:height=\"21\" krb:width=\"181\"><svg:rect krb:class=\"Label\" x=\"150\" y=\"175\" width=\"131\" height=\"21\" krb:text=\"PPT Channel 1 Failed Status\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".pptChannelFailed.failedChannel1\" x=\"281\" y=\"175\" width=\"50\" height=\"21\" "
        << "/>"
        << "</svg:g></svg:g><svg:rect krb:class=\"Label\" x=\"259\" y=\"590\" width=\"51\" height=\"21\" krb:text=\"32 | 10\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"19\" y=\"770\" width=\"371\" height=\"30\" krb:text=\"*** THIS CAN BREAK THE LADDER IF NOT SET CORRECTLY!\" krb:font=\"Source Sans Pro,10,-1,5,75,0,1,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".initSystem\" x=\"20\" y=\"110\" width=\"101\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".resetASICs\" x=\"20\" y=\"150\" width=\"101\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:g krb:direction=\"2\" krb:class=\"BoxLayout\" krb:x=\"150\" krb:y=\"20\" krb:height=\"96\" krb:width=\"180\"><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".startAllChannelsDummyData\" x=\"150\" y=\"20\" width=\"180\" height=\"23\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".stopAcquisition\" x=\"150\" y=\"43\" width=\"180\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".runXFEL\" x=\"150\" y=\"68\" width=\"180\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".stopStandalone\" x=\"150\" y=\"93\" width=\"180\" height=\"23\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"2\" krb:class=\"BoxLayout\" krb:x=\"350\" krb:y=\"150\" krb:height=\"46\" krb:width=\"214\"><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"350\" krb:y=\"150\" krb:height=\"21\" krb:width=\"214\"><svg:rect krb:class=\"Label\" x=\"350\" y=\"150\" width=\"129\" height=\"21\" krb:text=\"Last Train ID from PPT\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".lastTrainId\" x=\"479\" y=\"150\" width=\"85\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".readLastPPTTrainID\" x=\"350\" y=\"171\" width=\"214\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"2\" krb:class=\"BoxLayout\" krb:x=\"540\" krb:y=\"210\" krb:height=\"121\" krb:width=\"257\"><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"540\" krb:y=\"210\" krb:height=\"27\" krb:width=\"257\"><svg:rect krb:class=\"Label\" x=\"540\" y=\"210\" width=\"129\" height=\"27\" krb:text=\"Serial Number\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".iob1Status.iob1Serial\" x=\"669\" y=\"210\" width=\"128\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"540\" krb:y=\"237\" krb:height=\"68\" krb:width=\"257\"><svg:rect krb:class=\"Label\" x=\"540\" y=\"237\" width=\"127\" height=\"68\" krb:text=\"Firmware Buildstamp\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".iob1Status.iob1BuiltStamp\" x=\"667\" y=\"237\" width=\"130\" height=\"68\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"540\" krb:y=\"305\" krb:height=\"26\" krb:width=\"257\"><svg:rect krb:class=\"Label\" x=\"540\" y=\"305\" width=\"129\" height=\"26\" krb:text=\"IOB 1 Available\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCheckBox\" krb:keys=\"" << instanceId << ".iob1Status.iob1Available\" x=\"669\" y=\"305\" width=\"128\" height=\"26\" "
        << "/>"
        << "</svg:g></svg:g><svg:rect krb:class=\"Label\" x=\"150\" y=\"120\" width=\"72\" height=\"21\" krb:text=\"PLL Locked\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayColorBool\" krb:keys=\"" << instanceId << ".pptPLL.locked\" x=\"222\" y=\"120\" width=\"21\" height=\"21\" krb:invert=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"259\" y=\"610\" width=\"151\" height=\"31\" krb:text=\"4 = CL 50ns | 9 = CL 100ns\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"20\" y=\"240\" width=\"381\" height=\"21\" krb:text=\"1) Init system- IOB build must be 14003\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"20\" y=\"260\" width=\"381\" height=\"20\" krb:text=\"2) Change sequence box parameters according to red values\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"20\" y=\"280\" width=\"381\" height=\"20\" krb:text=\"3) Update counters\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:g krb:class=\"FixedLayout\" krb:x=\"19\" krb:y=\"370\" krb:height=\"403\" krb:width=\"241\"><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"370\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"370\" width=\"117\" height=\"27\" krb:text=\"Start Wait Time [?s] \" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.start_wait_time\" x=\"136\" y=\"370\" width=\"62\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.start_wait_time\" x=\"198\" y=\"370\" width=\"62\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"397\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"397\" width=\"122\" height=\"27\" krb:text=\"Start Wait Offset [?s] \" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.start_wait_offs\" x=\"141\" y=\"397\" width=\"60\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.start_wait_offs\" x=\"201\" y=\"397\" width=\"59\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"424\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"424\" width=\"110\" height=\"27\" krb:text=\"GDPS On Time [?s]\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.gdps_on_time\" x=\"129\" y=\"424\" width=\"66\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.gdps_on_time\" x=\"195\" y=\"424\" width=\"65\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"451\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"451\" width=\"107\" height=\"27\" krb:text=\"Iprog Length [cyc]\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.iprogLength\" x=\"126\" y=\"451\" width=\"67\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.iprogLength\" x=\"193\" y=\"451\" width=\"67\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"478\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"478\" width=\"107\" height=\"27\" krb:text=\"Burst Length [cyc]\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.burstLength\" x=\"126\" y=\"478\" width=\"67\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.burstLength\" x=\"193\" y=\"478\" width=\"67\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"505\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"505\" width=\"126\" height=\"27\" krb:text=\"Refpulse Length [cyc]\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.refpulseLength\" x=\"145\" y=\"505\" width=\"58\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.refpulseLength\" x=\"203\" y=\"505\" width=\"57\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"532\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"532\" width=\"97\" height=\"27\" krb:text=\"Fet On Time [?s]\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.fet_on_time\" x=\"116\" y=\"532\" width=\"72\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.fet_on_time\" x=\"188\" y=\"532\" width=\"72\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"559\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"559\" width=\"101\" height=\"27\" krb:text=\"CLR On Time [?s]\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.clr_on_time\" x=\"120\" y=\"559\" width=\"70\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.clr_on_time\" x=\"190\" y=\"559\" width=\"70\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"586\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"586\" width=\"81\" height=\"27\" krb:text=\"CLR On Cycle\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.clr_cycle\" x=\"100\" y=\"586\" width=\"80\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.clr_cycle\" x=\"180\" y=\"586\" width=\"80\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"613\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"613\" width=\"95\" height=\"27\" krb:text=\"CLR Duty [10ns]\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.clrDuty\" x=\"114\" y=\"613\" width=\"73\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.clrDuty\" x=\"187\" y=\"613\" width=\"73\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"640\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"640\" width=\"96\" height=\"27\" krb:text=\"Iprog Clr Enable\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.iprog_clr_en\" x=\"115\" y=\"640\" width=\"73\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.iprog_clr_en\" x=\"188\" y=\"640\" width=\"72\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"667\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"667\" width=\"97\" height=\"27\" krb:text=\"IProg Clear Duty\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.iprog_clr_duty\" x=\"116\" y=\"667\" width=\"72\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.iprog_clr_duty\" x=\"188\" y=\"667\" width=\"72\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"694\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"694\" width=\"103\" height=\"27\" krb:text=\"IProg clear Offset\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.iprog_clr_offset\" x=\"122\" y=\"694\" width=\"69\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.iprog_clr_offset\" x=\"191\" y=\"694\" width=\"69\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"19\" krb:y=\"721\" krb:height=\"27\" krb:width=\"241\"><svg:rect krb:class=\"Label\" x=\"19\" y=\"721\" width=\"114\" height=\"27\" krb:text=\"Power On Time [?s]\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequence.SW_PWR_ON\" x=\"133\" y=\"721\" width=\"64\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequence.SW_PWR_ON\" x=\"197\" y=\"721\" width=\"63\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".updateSequenceCounters\" x=\"19\" y=\"748\" width=\"241\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "</svg:g><svg:rect krb:class=\"Label\" x=\"259\" y=\"640\" width=\"61\" height=\"31\" krb:text=\"0\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"259\" y=\"560\" width=\"61\" height=\"21\" krb:text=\"5\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"259\" y=\"510\" width=\"61\" height=\"21\" krb:text=\"4\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"259\" y=\"420\" width=\"61\" height=\"31\" krb:text=\"3000\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"259\" y=\"370\" width=\"61\" height=\"31\" krb:text=\"15000\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"259\" y=\"720\" width=\"71\" height=\"21\" krb:text=\"20\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#aa0000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"19\" y=\"350\" width=\"89\" height=\"20\" krb:text=\"Sequence Box\" krb:font=\"Source Sans Pro,10,-1,5,75,0,0,0,0,0\" krb:foreground=\"\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect stroke=\"#000000\" stroke-opacity=\"1.0\" stroke-linecap=\"butt\" stroke-dashoffset=\"0.0\" stroke-width=\"1.0\" stroke-dasharray=\"\" stroke-style=\"1\" stroke-linejoin=\"miter\" stroke-miterlimit=\"4.0\" fill=\"none\" x=\"10\" y=\"350\" width=\"390\" height=\"450\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"20\" y=\"300\" width=\"431\" height=\"20\" krb:text=\"4) Run XFEL mode\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"20\" y=\"220\" width=\"381\" height=\"20\" krb:text=\"0) Instantiate karabo device\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"20\" y=\"200\" width=\"69\" height=\"20\" krb:text=\"Procedure\" krb:font=\"Source Sans Pro,10,-1,5,75,0,0,0,0,0\" krb:foreground=\"\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"20\" y=\"320\" width=\"481\" height=\"20\" krb:text=\"5) If U106/U107 currents vary more than 150uA STOP and check sequence box settings\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect stroke=\"#000000\" stroke-opacity=\"1.0\" stroke-linecap=\"butt\" stroke-dashoffset=\"0.0\" stroke-width=\"1.0\" stroke-dasharray=\"\" stroke-style=\"1\" stroke-linejoin=\"miter\" stroke-miterlimit=\"4.0\" fill=\"none\" x=\"10\" y=\"200\" width=\"483\" height=\"143\" "
        << "/>"
        << "<svg:g krb:direction=\"2\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"350\" krb:height=\"420\" krb:width=\"256\"><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"350\" krb:height=\"21\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"350\" width=\"128\" height=\"21\" krb:text=\"Operation Mode\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.opMode\" x=\"547\" y=\"350\" width=\"128\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"371\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"371\" width=\"85\" height=\"27\" krb:text=\"Cycle Length\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.cycleLength\" x=\"504\" y=\"371\" width=\"86\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.cycleLength\" x=\"590\" y=\"371\" width=\"85\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"398\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"398\" width=\"100\" height=\"27\" krb:text=\"Integration Time\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.integrationTime\" x=\"519\" y=\"398\" width=\"78\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.integrationTime\" x=\"597\" y=\"398\" width=\"78\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"425\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"425\" width=\"85\" height=\"27\" krb:text=\"Flattop\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.flattopLength\" x=\"504\" y=\"425\" width=\"86\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.flattopLength\" x=\"590\" y=\"425\" width=\"85\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"452\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"452\" width=\"85\" height=\"27\" krb:text=\"Ramp Length\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.rampLength\" x=\"504\" y=\"452\" width=\"86\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.rampLength\" x=\"590\" y=\"452\" width=\"85\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"479\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"479\" width=\"85\" height=\"27\" krb:text=\"Reset Length\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.resetLength\" x=\"504\" y=\"479\" width=\"86\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.resetLength\" x=\"590\" y=\"479\" width=\"85\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"506\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"506\" width=\"137\" height=\"27\" krb:text=\"Reset Integration Offset\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.resetIntegOffset\" x=\"556\" y=\"506\" width=\"60\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.resetIntegOffset\" x=\"616\" y=\"506\" width=\"59\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"533\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"533\" width=\"109\" height=\"27\" krb:text=\"Reset Hold Length\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.resetHoldLength\" x=\"528\" y=\"533\" width=\"74\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.resetHoldLength\" x=\"602\" y=\"533\" width=\"73\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"560\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"560\" width=\"118\" height=\"27\" krb:text=\"Flattop Hold Length\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.flattopHoldLength\" x=\"537\" y=\"560\" width=\"69\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.flattopHoldLength\" x=\"606\" y=\"560\" width=\"69\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"587\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"587\" width=\"139\" height=\"27\" krb:text=\"Ramp Integration Offset\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.rampIntegOffset\" x=\"558\" y=\"587\" width=\"59\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.rampIntegOffset\" x=\"617\" y=\"587\" width=\"58\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"614\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"614\" width=\"105\" height=\"27\" krb:text=\"Back Flip at Reset\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.backFlipAtReset\" x=\"524\" y=\"614\" width=\"76\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.backFlipAtReset\" x=\"600\" y=\"614\" width=\"75\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"641\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"641\" width=\"142\" height=\"27\" krb:text=\"Back Flip To Reset Offset\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.backFlipToResetOffset\" x=\"561\" y=\"641\" width=\"57\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.backFlipToResetOffset\" x=\"618\" y=\"641\" width=\"57\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"668\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"668\" width=\"155\" height=\"27\" krb:text=\"Single SH Cap Load Length\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.singleCapLoadLength\" x=\"574\" y=\"668\" width=\"50\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.singleCapLoadLength\" x=\"624\" y=\"668\" width=\"51\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"695\" krb:height=\"21\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"695\" width=\"118\" height=\"21\" krb:text=\"Single SH Cap Mode\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCheckBox\" krb:keys=\"" << instanceId << ".sequencer.singleSHCapMode\" x=\"537\" y=\"695\" width=\"69\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"EditableCheckBox\" krb:keys=\"" << instanceId << ".sequencer.singleSHCapMode\" x=\"606\" y=\"695\" width=\"69\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"716\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"716\" width=\"140\" height=\"27\" krb:text=\"Inject Rising Edge Offset\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.injectRisingEdgeOffset\" x=\"559\" y=\"716\" width=\"58\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.injectRisingEdgeOffset\" x=\"617\" y=\"716\" width=\"58\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"419\" krb:y=\"743\" krb:height=\"27\" krb:width=\"256\"><svg:rect krb:class=\"Label\" x=\"419\" y=\"743\" width=\"115\" height=\"27\" krb:text=\"Empty Inject Cycles\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".sequencer.emptyInjectCycles\" x=\"534\" y=\"743\" width=\"71\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".sequencer.emptyInjectCycles\" x=\"605\" y=\"743\" width=\"70\" height=\"27\" "
        << "/>"
        << "</svg:g></svg:g><svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCommand\" krb:keys=\"" << instanceId << ".updateSequencer\" x=\"420\" y=\"770\" width=\"256\" height=\"25\" krb:requires_confirmation=\"false\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"350\" y=\"110\" width=\"151\" height=\"21\" krb:text=\"Disable Sending\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCheckBox\" krb:keys=\"" << instanceId << ".disable_sending\" x=\"500\" y=\"110\" width=\"57\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"EditableCheckBox\" krb:keys=\"" << instanceId << ".disable_sending\" x=\"550\" y=\"110\" width=\"21\" height=\"21\" "
        << "/>"
        << "<svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"580\" krb:y=\"45\" krb:height=\"27\" krb:width=\"222\"><svg:rect krb:class=\"Label\" x=\"580\" y=\"45\" width=\"121\" height=\"27\" krb:text=\"Num Frames in Train\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".numFramesToSendOut\" x=\"701\" y=\"45\" width=\"50\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".numFramesToSendOut\" x=\"751\" y=\"45\" width=\"51\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"580\" krb:y=\"72\" krb:height=\"27\" krb:width=\"222\"><svg:rect krb:class=\"Label\" x=\"580\" y=\"72\" width=\"120\" height=\"27\" krb:text=\"Num Pre Burst Vetos\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".numPreBurstVetos\" x=\"700\" y=\"72\" width=\"51\" height=\"27\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"IntLineEdit\" krb:keys=\"" << instanceId << ".numPreBurstVetos\" x=\"751\" y=\"72\" width=\"51\" height=\"27\" "
        << "/>"
        << "</svg:g><svg:g krb:direction=\"0\" krb:class=\"BoxLayout\" krb:x=\"580\" krb:y=\"99\" krb:height=\"21\" krb:width=\"222\"><svg:rect krb:class=\"Label\" x=\"580\" y=\"99\" width=\"80\" height=\"21\" krb:text=\"XFEL Control\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayCheckBox\" krb:keys=\"" << instanceId << ".xfelMode\" x=\"660\" y=\"99\" width=\"71\" height=\"21\" "
        << "/>"
        << "<svg:rect krb:class=\"EditableApplyLaterComponent\" krb:widget=\"EditableCheckBox\" krb:keys=\"" << instanceId << ".xfelMode\" x=\"731\" y=\"99\" width=\"71\" height=\"21\" "
        << "/>"
        << "</svg:g><svg:rect krb:class=\"Label\" x=\"10\" y=\"850\" width=\"91\" height=\"27\" krb:text=\"Full Config File\" krb:font=\"Source Sans Pro,10,-1,5,50,0,0,0,0,0\" krb:foreground=\"#000000\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "<svg:rect krb:class=\"DisplayComponent\" krb:widget=\"DisplayLabel\" krb:keys=\"" << instanceId << ".fullConfigFileName\" x=\"100\" y=\"840\" width=\"681\" height=\"41\" "
        << "/>"
        << "<svg:rect krb:class=\"Label\" x=\"19\" y=\"0\" width=\"751\" height=\"20\" krb:text=\"DSSC " << quadrantId << " Configurator\" krb:font=\"Source Sans Pro,10,-1,5,75,0,0,0,0,0\" krb:foreground=\"#0000ff\" krb:frameWidth=\"0\" krb:background=\"transparent\" "
        << "/>"
        << "</svg:svg>"

        << "";
    return ret.str();
}
